package model;
// Generated Sep 28, 2014 2:53:00 PM by Hibernate Tools 3.6.0



/**
 * Followers generated by hbm2java
 */
public class Followers  implements java.io.Serializable {


     private FollowersId id;
     private Users usersByFollowerId;
     private Users usersByUserId;

    public Followers() {
    }

    public Followers(FollowersId id, Users usersByFollowerId, Users usersByUserId) {
       this.id = id;
       this.usersByFollowerId = usersByFollowerId;
       this.usersByUserId = usersByUserId;
    }
   
    public FollowersId getId() {
        return this.id;
    }
    
    public void setId(FollowersId id) {
        this.id = id;
    }
    public Users getUsersByFollowerId() {
        return this.usersByFollowerId;
    }
    
    public void setUsersByFollowerId(Users usersByFollowerId) {
        this.usersByFollowerId = usersByFollowerId;
    }
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }
    
    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }




}


