package model;
// Generated Sep 28, 2014 2:53:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer postId;
     private Users users;
     private String title;
     private String image;
     private String content;
     private Date createdAt;
     private Set commentses = new HashSet(0);
     private Set notificationses = new HashSet(0);
     private Set likeses = new HashSet(0);

    public Posts() {
    }

	
    public Posts(Users users, String title, String image, String content, Date createdAt) {
        this.users = users;
        this.title = title;
        this.image = image;
        this.content = content;
        this.createdAt = createdAt;
    }
    public Posts(Users users, String title, String image, String content, Date createdAt, Set commentses, Set notificationses, Set likeses) {
       this.users = users;
       this.title = title;
       this.image = image;
       this.content = content;
       this.createdAt = createdAt;
       this.commentses = commentses;
       this.notificationses = notificationses;
       this.likeses = likeses;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getNotificationses() {
        return this.notificationses;
    }
    
    public void setNotificationses(Set notificationses) {
        this.notificationses = notificationses;
    }
    public Set getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set likeses) {
        this.likeses = likeses;
    }




}


