package model;
// Generated Sep 28, 2014 2:53:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String username;
     private String email;
     private Date birthday;
     private String password;
     private String description;
     private String blogTitle;
     private Date registeredAt;
     private Date lastLogin;
     private Set commentses = new HashSet(0);
     private Set followersesForFollowerId = new HashSet(0);
     private Set notificationsesForUserId = new HashSet(0);
     private Set notificationsesForFromUserId = new HashSet(0);
     private Set postses = new HashSet(0);
     private Set likeses = new HashSet(0);
     private Settings settings;
     private Set followersesForUserId = new HashSet(0);

    public Users() {
    }

	
    public Users(String name, String username, String email, Date birthday, String password, String description, String blogTitle, Date registeredAt, Date lastLogin) {
        this.name = name;
        this.username = username;
        this.email = email;
        this.birthday = birthday;
        this.password = password;
        this.description = description;
        this.blogTitle = blogTitle;
        this.registeredAt = registeredAt;
        this.lastLogin = lastLogin;
    }
    public Users(String name, String username, String email, Date birthday, String password, String description, String blogTitle, Date registeredAt, Date lastLogin, Set commentses, Set followersesForFollowerId, Set notificationsesForUserId, Set notificationsesForFromUserId, Set postses, Set likeses, Settings settings, Set followersesForUserId) {
       this.name = name;
       this.username = username;
       this.email = email;
       this.birthday = birthday;
       this.password = password;
       this.description = description;
       this.blogTitle = blogTitle;
       this.registeredAt = registeredAt;
       this.lastLogin = lastLogin;
       this.commentses = commentses;
       this.followersesForFollowerId = followersesForFollowerId;
       this.notificationsesForUserId = notificationsesForUserId;
       this.notificationsesForFromUserId = notificationsesForFromUserId;
       this.postses = postses;
       this.likeses = likeses;
       this.settings = settings;
       this.followersesForUserId = followersesForUserId;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBlogTitle() {
        return this.blogTitle;
    }
    
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle;
    }
    public Date getRegisteredAt() {
        return this.registeredAt;
    }
    
    public void setRegisteredAt(Date registeredAt) {
        this.registeredAt = registeredAt;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getFollowersesForFollowerId() {
        return this.followersesForFollowerId;
    }
    
    public void setFollowersesForFollowerId(Set followersesForFollowerId) {
        this.followersesForFollowerId = followersesForFollowerId;
    }
    public Set getNotificationsesForUserId() {
        return this.notificationsesForUserId;
    }
    
    public void setNotificationsesForUserId(Set notificationsesForUserId) {
        this.notificationsesForUserId = notificationsesForUserId;
    }
    public Set getNotificationsesForFromUserId() {
        return this.notificationsesForFromUserId;
    }
    
    public void setNotificationsesForFromUserId(Set notificationsesForFromUserId) {
        this.notificationsesForFromUserId = notificationsesForFromUserId;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }
    public Set getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set likeses) {
        this.likeses = likeses;
    }
    public Settings getSettings() {
        return this.settings;
    }
    
    public void setSettings(Settings settings) {
        this.settings = settings;
    }
    public Set getFollowersesForUserId() {
        return this.followersesForUserId;
    }
    
    public void setFollowersesForUserId(Set followersesForUserId) {
        this.followersesForUserId = followersesForUserId;
    }




}


