package model;
// Generated Sep 28, 2014 3:01:04 PM by Hibernate Tools 4.3.1



/**
 * Likes generated by hbm2java
 */
public class Likes  implements java.io.Serializable {


     private Integer likeId;
     private Posts posts;
     private Users users;

    public Likes() {
    }

    public Likes(Posts posts, Users users) {
       this.posts = posts;
       this.users = users;
    }
   
    public Integer getLikeId() {
        return this.likeId;
    }
    
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


