package model;
// Generated Oct 13, 2014 2:34:17 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notifications generated by hbm2java
 */
public class Notifications  implements java.io.Serializable {


     private Integer notificationId;
     private Posts posts;
     private Users usersByUserId;
     private Users usersByFromUserId;
     private int notificationType;
     private Date seenAt;

    public Notifications() {
    }

    public Notifications(Posts posts, Users usersByUserId, Users usersByFromUserId, int notificationType, Date seenAt) {
       this.posts = posts;
       this.usersByUserId = usersByUserId;
       this.usersByFromUserId = usersByFromUserId;
       this.notificationType = notificationType;
       this.seenAt = seenAt;
    }
   
    public Integer getNotificationId() {
        return this.notificationId;
    }
    
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }
    public Users getUsersByUserId() {
        return this.usersByUserId;
    }
    
    public void setUsersByUserId(Users usersByUserId) {
        this.usersByUserId = usersByUserId;
    }
    public Users getUsersByFromUserId() {
        return this.usersByFromUserId;
    }
    
    public void setUsersByFromUserId(Users usersByFromUserId) {
        this.usersByFromUserId = usersByFromUserId;
    }
    public int getNotificationType() {
        return this.notificationType;
    }
    
    public void setNotificationType(int notificationType) {
        this.notificationType = notificationType;
    }
    public Date getSeenAt() {
        return this.seenAt;
    }
    
    public void setSeenAt(Date seenAt) {
        this.seenAt = seenAt;
    }




}


