package model;
// Generated Oct 4, 2014 6:56:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer postId;
     private Users users;
     private String title;
     private String image;
     private String content;
     private Date createdAt;
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<Notifications> notificationses = new HashSet<Notifications>(0);
     private Set<Likes> likeses = new HashSet<Likes>(0);

    public Posts() {
    }

	
    public Posts(Users users, String title, String image, String content, Date createdAt) {
        this.users = users;
        this.title = title;
        this.image = image;
        this.content = content;
        this.createdAt = createdAt;
    }
    public Posts(Users users, String title, String image, String content, Date createdAt, Set<Comments> commentses, Set<Notifications> notificationses, Set<Likes> likeses) {
       this.users = users;
       this.title = title;
       this.image = image;
       this.content = content;
       this.createdAt = createdAt;
       this.commentses = commentses;
       this.notificationses = notificationses;
       this.likeses = likeses;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
    public Set<Notifications> getNotificationses() {
        return this.notificationses;
    }
    
    public void setNotificationses(Set<Notifications> notificationses) {
        this.notificationses = notificationses;
    }
    public Set<Likes> getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set<Likes> likeses) {
        this.likeses = likeses;
    }




}


