package model;
// Generated Oct 13, 2014 2:34:17 PM by Hibernate Tools 4.3.1



/**
 * Settings generated by hbm2java
 */
public class Settings  implements java.io.Serializable {


     private int userId;
     private Users users;
     private int username;
     private int realname;
     private int birthday;
     private int email;
     private int newFollower;
     private int newLikes;
     private int newComment;

    public Settings() {
    }

    public Settings(Users users, int username, int realname, int birthday, int email, int newFollower, int newLikes, int newComment) {
       this.users = users;
       this.username = username;
       this.realname = realname;
       this.birthday = birthday;
       this.email = email;
       this.newFollower = newFollower;
       this.newLikes = newLikes;
       this.newComment = newComment;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getUsername() {
        return this.username;
    }
    
    public void setUsername(int username) {
        this.username = username;
    }
    public int getRealname() {
        return this.realname;
    }
    
    public void setRealname(int realname) {
        this.realname = realname;
    }
    public int getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(int birthday) {
        this.birthday = birthday;
    }
    public int getEmail() {
        return this.email;
    }
    
    public void setEmail(int email) {
        this.email = email;
    }
    public int getNewFollower() {
        return this.newFollower;
    }
    
    public void setNewFollower(int newFollower) {
        this.newFollower = newFollower;
    }
    public int getNewLikes() {
        return this.newLikes;
    }
    
    public void setNewLikes(int newLikes) {
        this.newLikes = newLikes;
    }
    public int getNewComment() {
        return this.newComment;
    }
    
    public void setNewComment(int newComment) {
        this.newComment = newComment;
    }




}


