package model;
// Generated Oct 7, 2014 11:51:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String username;
     private String email;
     private Date birthday;
     private String password;
     private String description;
     private String blogTitle;
     private Date registeredAt;
     private Date lastLogin;
     private String picturePath;
     private Set<Comments> commentses = new HashSet<Comments>(0);
     private Set<Followers> followersesForFollowerId = new HashSet<Followers>(0);
     private Set<Notifications> notificationsesForUserId = new HashSet<Notifications>(0);
     private Set<Notifications> notificationsesForFromUserId = new HashSet<Notifications>(0);
     private Set<Posts> postses = new HashSet<Posts>(0);
     private Set<Likes> likeses = new HashSet<Likes>(0);
     private Settings settings;
     private Set<Followers> followersesForUserId = new HashSet<Followers>(0);

    public Users() {
    }

	
    public Users(String name, String username, String email, Date birthday, String password, String description, String blogTitle, Date registeredAt, Date lastLogin, String picturePath) {
        this.name = name;
        this.username = username;
        this.email = email;
        this.birthday = birthday;
        this.password = password;
        this.description = description;
        this.blogTitle = blogTitle;
        this.registeredAt = registeredAt;
        this.lastLogin = lastLogin;
        this.picturePath = picturePath;
    }
    public Users(String name, String username, String email, Date birthday, String password, String description, String blogTitle, Date registeredAt, Date lastLogin, String picturePath, Set<Comments> commentses, Set<Followers> followersesForFollowerId, Set<Notifications> notificationsesForUserId, Set<Notifications> notificationsesForFromUserId, Set<Posts> postses, Set<Likes> likeses, Settings settings, Set<Followers> followersesForUserId) {
       this.name = name;
       this.username = username;
       this.email = email;
       this.birthday = birthday;
       this.password = password;
       this.description = description;
       this.blogTitle = blogTitle;
       this.registeredAt = registeredAt;
       this.lastLogin = lastLogin;
       this.picturePath = picturePath;
       this.commentses = commentses;
       this.followersesForFollowerId = followersesForFollowerId;
       this.notificationsesForUserId = notificationsesForUserId;
       this.notificationsesForFromUserId = notificationsesForFromUserId;
       this.postses = postses;
       this.likeses = likeses;
       this.settings = settings;
       this.followersesForUserId = followersesForUserId;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getBlogTitle() {
        return this.blogTitle;
    }
    
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle;
    }
    public Date getRegisteredAt() {
        return this.registeredAt;
    }
    
    public void setRegisteredAt(Date registeredAt) {
        this.registeredAt = registeredAt;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public String getPicturePath() {
        return this.picturePath;
    }
    
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }
    public Set<Comments> getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set<Comments> commentses) {
        this.commentses = commentses;
    }
    public Set<Followers> getFollowersesForFollowerId() {
        return this.followersesForFollowerId;
    }
    
    public void setFollowersesForFollowerId(Set<Followers> followersesForFollowerId) {
        this.followersesForFollowerId = followersesForFollowerId;
    }
    public Set<Notifications> getNotificationsesForUserId() {
        return this.notificationsesForUserId;
    }
    
    public void setNotificationsesForUserId(Set<Notifications> notificationsesForUserId) {
        this.notificationsesForUserId = notificationsesForUserId;
    }
    public Set<Notifications> getNotificationsesForFromUserId() {
        return this.notificationsesForFromUserId;
    }
    
    public void setNotificationsesForFromUserId(Set<Notifications> notificationsesForFromUserId) {
        this.notificationsesForFromUserId = notificationsesForFromUserId;
    }
    public Set<Posts> getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set<Posts> postses) {
        this.postses = postses;
    }
    public Set<Likes> getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set<Likes> likeses) {
        this.likeses = likeses;
    }
    public Settings getSettings() {
        return this.settings;
    }
    
    public void setSettings(Settings settings) {
        this.settings = settings;
    }
    public Set<Followers> getFollowersesForUserId() {
        return this.followersesForUserId;
    }
    
    public void setFollowersesForUserId(Set<Followers> followersesForUserId) {
        this.followersesForUserId = followersesForUserId;
    }




}


